#!/usr/bin/env bash
# Bash script that manages the manage_my_process process
. /lib/lsb/init-functions

PIDFILE=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
}

stop() {
    kill "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
}

case "$1" in 
    start)
        start
        log_success_msg "manage_my_process started"
        ;;
    stop)
        stop
        log_success_msg "manage_my_process stopped"
        ;;
    restart)
        stop
        start
        log_success_msg "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
