#!/usr/bin/env bash

# Extract the IP and HTTP status code fields from the Apache log file and group by IP and HTTP status code,

awk '{print $1" "$9}' apache-access.log | sort | uniq -c | awk '{print $1" "$2" "$3}' | sort -nr | sed 's/^ *//g' | sed 's/ /\t/g'
