#!/usr/bin/env bash
# this script print best school and hi on the 9th line using while loop
count=1

while [ $count -le 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((count++))
done
