#!/usr/bin/env bash
#this prints best school and bad luck 4th and good luck on 8th iteration using while loop
count=1

while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
