#!/usr/bin/env bash
#prints clock in hours andin minutes
hour=0
minute=1

while [ $hour -lt 13 ]
do
  while [ $minute -lt 60 ]
  do
    printf "%02d:%02d\n" $hour $minute
    ((minute++))
  done
  minute=0
  ((hour++))
done
